name: "Workflow Dispatch by Slack"
description: "Trigger workflow_dispatch event using Slack"
branding:
  icon: "send"
  color: "green"
inputs:
  repository:
    description: "Target repository"
    default: ${{ github.repository }}
  workflow:
    description: "Workflow ID or filename for ok"
    required: true
  cancel-workflow:
    description: "Workflow ID or filename for cancel"
  ref:
    description: "Workflow ref"
  inputs:
    description: "Workflow inputs"
  cancel-inputs:
    description: "Cancel workflow inputs"
  github-token:
    description: "GitHub token"
  default-github-token:
    description: "Default GitHub token"
    default: ${{ github.token }}
  channel:
    description: "Slack Channel ID or name"
    required: true
  slack-bot-token:
    description: "Slack bot token"
  slack-webhook-url:
    description: "Slack webhook URL"
  mention:
    description: "Slack user to mention"
  button:
    description: "button name"
    default: '{"ok": "OK", "cancel": "Cancel"}'
runs:
  using: "node20"
  main: "dist/index.js"
